# Generated by Django 3.1.7 on 2021-03-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auth_follow_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='group',
        ),
    ]
