# Generated by Django 3.1.7 on 2021-03-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210311_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
